/**
 * 写型思源冒烟共享防线。
 *
 * 默认只允许在空的隔离靶场运行：临时笔记本使用本插件前缀，启动时清扫
 * 同前缀残留，发现任何其它笔记本就拒绝写入。外部目标必须显式提供
 * SIYUAN_BASE_URL + SIYUAN_TOKEN；不内置真实地址的 token。
 */
export const SCRATCH_PREFIXES = [
    "lvct-contacts-smoke-",
    "lvct-contacts-e2e-",
];

export function isScratchName(name) {
    // Only names generated by the current runners are disposable. Legacy exact
    // names (for example `人脉-E2E` or `RenmaiSpike`) may belong to a user's
    // workspace and must never be deleted by an external-target smoke run.
    return typeof name === "string" && SCRATCH_PREFIXES.some((prefix) => name.startsWith(prefix));
}

export function resolveTarget({ baseArg, tokenArg, requireToken = true } = {}) {
    const rawBase = baseArg ?? process.env.SIYUAN_BASE_URL;
    if (!rawBase) throw new Error("缺少思源地址：请设置 SIYUAN_BASE_URL 或传入 --base-url；不会偷偷连接默认内核");
    const base = String(rawBase).replace(/\/+$/, "");
    const token = String(tokenArg ?? process.env.SIYUAN_TOKEN ?? "");
    if (requireToken && !token) throw new Error("缺少思源 token：请设置 SIYUAN_TOKEN 或传入 token；不会使用默认 token");
    return { base, token };
}

/** v3.8.6+ stores the local API token under api.token; older builds used accessAuthCode. */
export function kernelTokenFromConfig(config) {
    if (!config || typeof config !== "object" || Array.isArray(config)) return "";
    const record = config;
    const token = record.api && typeof record.api === "object" && !Array.isArray(record.api)
        ? record.api.token
        : undefined;
    return String(token ?? record.accessAuthCode ?? "").trim();
}

export function makeApi(base, token, { signalMs = 5000 } = {}) {
    return async function api(path, body = {}) {
        const response = await fetch(`${base}${path}`, {
            method: "POST",
            headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Token ${token}` } : {}) },
            body: JSON.stringify(body),
            signal: AbortSignal.timeout(signalMs),
        });
        if (!response.ok) throw new Error(`HTTP ${response.status} ${path}`);
        const text = await response.text();
        return text ? JSON.parse(text) : {};
    };
}

async function listNotebooks(api) {
    const payload = await api("/api/notebook/lsNotebooks", {});
    if (payload.code !== 0) throw new Error(`lsNotebooks code=${payload.code} msg=${payload.msg}`);
    return payload.data?.notebooks ?? [];
}

/**
 * 只删除自己注册的临时库；清扫失败必须阻止后续写入，避免把未清理的
 * 临时库误当作干净靶场继续使用。
 */
export async function sweepOrphans(api) {
    const orphans = (await listNotebooks(api)).filter((notebook) => isScratchName(notebook.name));
    const failures = [];
    for (const notebook of orphans) {
        try {
            const result = await api("/api/notebook/removeNotebook", { notebook: notebook.id });
            if (result.code !== 0) throw new Error(`code=${result.code} msg=${result.msg}`);
            console.log(`  清扫残留临时库：${notebook.name}`);
        } catch (error) {
            console.warn(`  WARN 残留清理失败（不删除其它数据）：${notebook.name} — ${String(error).slice(0, 120)}`);
            failures.push(notebook.name);
        }
    }
    if (failures.length) {
        throw new Error(`临时库清扫失败：${failures.join("、")}；为避免污染工作区，已阻止后续写入`);
    }
}

/** 写型冒烟靶场存在真实笔记本时拒跑；共享运行必须显式豁免。 */
export async function guardScratch(api, { base = "" } = {}) {
    const notebooks = await listNotebooks(api);
    const foreign = notebooks.filter((notebook) => !isScratchName(notebook.name));
    if (!foreign.length) return;
    if (process.env.SIYUAN_E2E_ALLOW_SHARED === "1") {
        console.warn(`WARN SIYUAN_E2E_ALLOW_SHARED=1：目标 ${base} 含 ${foreign.length} 个非临时库，测试写入风险由调用者承担`);
        return;
    }
    throw new Error([
        `拒绝写型冒烟：目标 ${base} 存在非临时笔记本「${foreign[0].name}」`,
        "请使用独立 workspace 启动第二个思源实例（建议端口 6807/自动顺延），只安装被测插件。",
        "如确认风险并确实要共用内核，请显式设置 SIYUAN_E2E_ALLOW_SHARED=1。",
    ].join("\n"));
}

export function aiEnabled() {
    return process.env.SIYUAN_E2E_AI === "1";
}

export async function deleteScratchNotebook(api, notebookId) {
    if (!notebookId) return;
    const result = await api("/api/notebook/removeNotebook", { notebook: notebookId });
    if (result.code !== 0) throw new Error(`临时库清理失败 code=${result.code} msg=${result.msg}`);
}
